# Generated by Django 4.2 on 2026-01-04 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_complaint', 'New Complaint'), ('new_user', 'New User'), ('status_change', 'Status Change'), ('system_alert', 'System Alert'), ('feedback', 'New Feedback'), ('assigned', 'Complaint Assigned'), ('high_priority', 'High Priority Alert')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('related_model', models.CharField(blank=True, max_length=50, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Admin Notification',
                'verbose_name_plural': 'Admin Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('alert_type', models.CharField(choices=[('pending_time', 'Complaint Pending Too Long'), ('high_volume', 'High Complaint Volume'), ('low_satisfaction', 'Low Satisfaction Score'), ('department_overload', 'Department Overloaded')], max_length=50)),
                ('condition', models.JSONField(help_text='JSON condition parameters')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alert Rule',
                'verbose_name_plural': 'Alert Rules',
                'ordering': ['-severity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QuickAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('action_type', models.CharField(choices=[('resolve', 'Mark as Resolved'), ('assign', 'Assign to Department'), ('escalate', 'Escalate'), ('follow_up', 'Schedule Follow-up'), ('export', 'Export Data')], max_length=20)),
                ('icon', models.CharField(help_text='FontAwesome icon class', max_length=50)),
                ('description', models.TextField()),
                ('shortcut_key', models.CharField(blank=True, help_text='Keyboard shortcut', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Quick Action',
                'verbose_name_plural': 'Quick Actions',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('setting_type', models.CharField(choices=[('general', 'General'), ('email', 'Email'), ('notification', 'Notification'), ('analytics', 'Analytics'), ('security', 'Security')], default='general', max_length=20)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
                'ordering': ['setting_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('complaints_summary', 'Complaints Summary'), ('user_activity', 'User Activity'), ('sentiment_analysis', 'Sentiment Analysis'), ('department_performance', 'Department Performance'), ('ai_interactions', 'AI Interactions')], max_length=50)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('columns', models.JSONField(blank=True, default=list)),
                ('is_public', models.BooleanField(default=False, help_text='Visible to all admins')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_generated', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Report',
                'verbose_name_plural': 'Saved Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('daily_complaints', 'Daily Complaints'), ('weekly_resolutions', 'Weekly Resolutions'), ('user_registrations', 'User Registrations'), ('avg_resolution_time', 'Average Resolution Time'), ('satisfaction_score', 'Satisfaction Score')], max_length=50)),
                ('value', models.FloatField()),
                ('date', models.DateField()),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dashboard Metric',
                'verbose_name_plural': 'Dashboard Metrics',
                'ordering': ['-date', 'metric_type'],
                'unique_together': {('metric_type', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('resolve', 'Resolve'), ('assign', 'Assign'), ('export', 'Export'), ('bulk', 'Bulk Operation')], max_length=20)),
                ('model_name', models.CharField(max_length=50)),
                ('object_id', models.IntegerField()),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Log',
                'verbose_name_plural': 'Admin Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
