# Generated by Django 4.2 on 2026-01-04 13:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pulse_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='FontAwesome icon class', max_length=50)),
                ('color', models.CharField(default='#3b82f6', help_text='Hex color code', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_id', models.CharField(help_text='Auto-generated ID', max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Escalated', 'Escalated'), ('Rejected', 'Rejected')], default='Submitted', max_length=20)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20)),
                ('address', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=15)),
                ('image', models.ImageField(blank=True, null=True, upload_to='complaints/images/')),
                ('document', models.FileField(blank=True, null=True, upload_to='complaints/documents/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('upvotes', models.IntegerField(default=0)),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_assigned_complaints', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='pulse_admin.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_complaints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.RemoveField(
            model_name='adminnotification',
            name='related_model',
        ),
        migrations.RemoveField(
            model_name='adminnotification',
            name='related_object_id',
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adminlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('resolve', 'Resolve'), ('assign', 'Assign'), ('escalate', 'Escalate'), ('export', 'Export'), ('bulk', 'Bulk Operation')], max_length=20),
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='notification_type',
            field=models.CharField(choices=[('new_complaint', 'New Complaint'), ('new_user', 'New User'), ('status_change', 'Status Change'), ('system_alert', 'System Alert'), ('feedback', 'New Feedback'), ('assigned', 'Complaint Assigned'), ('high_priority', 'High Priority Alert'), ('escalated', 'Complaint Escalated')], max_length=20),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='alert_type',
            field=models.CharField(choices=[('pending_time', 'Complaint Pending Too Long'), ('high_volume', 'High Complaint Volume'), ('low_satisfaction', 'Low Satisfaction Score'), ('department_overload', 'Department Overloaded'), ('high_priority_pending', 'High Priority Pending'), ('no_update', 'No Update in 48 Hours')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dashboardmetric',
            name='metric_type',
            field=models.CharField(choices=[('total_complaints', 'Total Complaints'), ('resolved_today', 'Resolved Today'), ('pending_complaints', 'Pending Complaints'), ('avg_resolution_time', 'Average Resolution Time (hours)'), ('user_satisfaction', 'User Satisfaction Score'), ('high_priority_count', 'High Priority Complaints'), ('category_distribution', 'Category Distribution'), ('status_distribution', 'Status Distribution')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dashboardmetric',
            name='value',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='quickaction',
            name='action_type',
            field=models.CharField(choices=[('resolve', 'Mark as Resolved'), ('assign', 'Assign to Department'), ('escalate', 'Escalate Priority'), ('follow_up', 'Schedule Follow-up'), ('export', 'Export Data'), ('message', 'Message User'), ('view_details', 'View Details')], max_length=20),
        ),
        migrations.AlterField(
            model_name='savedreport',
            name='report_type',
            field=models.CharField(choices=[('complaints_summary', 'Complaints Summary'), ('user_activity', 'User Activity'), ('sentiment_analysis', 'Sentiment Analysis'), ('department_performance', 'Department Performance'), ('resolution_timeline', 'Resolution Timeline'), ('category_analysis', 'Category Analysis')], max_length=50),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='setting_type',
            field=models.CharField(choices=[('general', 'General'), ('email', 'Email'), ('notification', 'Notification'), ('analytics', 'Analytics'), ('security', 'Security'), ('priority', 'Priority Settings')], default='general', max_length=20),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'Very Dissatisfied'), (2, 'Dissatisfied'), (3, 'Neutral'), (4, 'Satisfied'), (5, 'Very Satisfied')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=True, help_text='Show this feedback publicly')),
                ('complaint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='pulse_admin.complaint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('head', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('comment', models.TextField()),
                ('is_internal', models.BooleanField(default=False, help_text='Internal note not visible to citizen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='pulse_admin.complaint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='related_complaint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='pulse_admin.complaint'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['status'], name='pulse_admin_status_83658b_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['priority'], name='pulse_admin_priorit_f90c65_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['category'], name='pulse_admin_categor_50ae55_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['submitted_at'], name='pulse_admin_submitt_9b8c30_idx'),
        ),
    ]
