# Generated by Django 4.2 on 2026-01-31 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse_admin', '0002_category_complaint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlog',
            name='object_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='condition',
            field=models.JSONField(default=dict, help_text='JSON condition parameters'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_id',
            field=models.CharField(editable=False, help_text='Auto-generated ID', max_length=20, unique=True),
        ),
    ]
