# Generated by Django 4.2 on 2026-02-02 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pulse_admin', '0003_alter_adminlog_object_id_alter_alertrule_condition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='Officer', help_text='Role in department', max_length=50)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('can_assign', models.BooleanField(default=False, help_text='Can assign complaints to others')),
                ('can_resolve', models.BooleanField(default=True, help_text='Can resolve complaints')),
                ('can_escalate', models.BooleanField(default=False, help_text='Can escalate complaints')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Department User',
                'verbose_name_plural': 'Department Users',
                'ordering': ['department__name', 'user__username'],
            },
        ),
        migrations.DeleteModel(
            name='AlertRule',
        ),
        migrations.RemoveField(
            model_name='complaintupdate',
            name='complaint',
        ),
        migrations.RemoveField(
            model_name='complaintupdate',
            name='user',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='complaint',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
        migrations.RemoveField(
            model_name='savedreport',
            name='created_by',
        ),
        migrations.AlterUniqueTogether(
            name='dashboardmetric',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='adminnotification',
            name='related_complaint',
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pulse_admin.department'),
        ),
        migrations.AddField(
            model_name='dashboardmetric',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pulse_admin.department'),
        ),
        migrations.AddField(
            model_name='department',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='department',
            name='category',
            field=models.CharField(choices=[('municipal', 'Municipal Issues'), ('electricity', 'Electricity'), ('water', 'Water Supply'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('transport', 'Transport'), ('corruption', 'Corruption & Bribery'), ('safety', 'Public Safety'), ('general', 'General Complaint')], default='general', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quickaction',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Administrator'), ('department', 'Department'), ('both', 'Both')], default='admin', max_length=20),
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='notification_type',
            field=models.CharField(choices=[('new_complaint', 'New Complaint'), ('new_user', 'New User'), ('status_change', 'Status Change'), ('system_alert', 'System Alert'), ('feedback', 'New Feedback'), ('assigned', 'Complaint Assigned'), ('high_priority', 'High Priority Alert'), ('escalated', 'Complaint Escalated'), ('department_assigned', 'Department Assigned')], max_length=20),
        ),
        migrations.AlterField(
            model_name='dashboardmetric',
            name='metric_type',
            field=models.CharField(choices=[('total_complaints', 'Total Complaints'), ('resolved_today', 'Resolved Today'), ('pending_complaints', 'Pending Complaints'), ('user_satisfaction', 'User Satisfaction Score'), ('high_priority_count', 'High Priority Complaints'), ('department_resolved', 'Department Resolved')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dashboardmetric',
            name='value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='quickaction',
            name='action_type',
            field=models.CharField(choices=[('resolve', 'Mark as Resolved'), ('assign', 'Assign to Department'), ('escalate', 'Escalate Priority'), ('follow_up', 'Schedule Follow-up'), ('export', 'Export Data'), ('message', 'Message User'), ('view_details', 'View Details'), ('reassign', 'Reassign Complaint')], max_length=20),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='setting_type',
            field=models.CharField(choices=[('general', 'General'), ('email', 'Email'), ('notification', 'Notification'), ('analytics', 'Analytics'), ('security', 'Security'), ('priority', 'Priority Settings'), ('department', 'Department Settings')], default='general', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='dashboardmetric',
            unique_together={('metric_type', 'date', 'department')},
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
        migrations.DeleteModel(
            name='ComplaintUpdate',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='SavedReport',
        ),
        migrations.AddField(
            model_name='departmentuser',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='pulse_admin.department'),
        ),
        migrations.AddField(
            model_name='departmentuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='department_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
