# Generated by Django 5.2.9 on 2026-02-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse_admin', '0004_departmentuser_delete_alertrule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly name', null=True, unique=True),
        ),
    ]
