# Generated by Django 5.2.9 on 2026-02-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse_admin', '0006_alter_department_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=120, unique=True),
        ),
    ]
