# Generated by Django 5.2.9 on 2025-12-26 11:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('head', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_id', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('landmark', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(choices=[('Municipal Issues', 'Municipal Issues'), ('Electricity', 'Electricity'), ('Water Supply', 'Water Supply'), ('Healthcare', 'Healthcare'), ('Education', 'Education'), ('Transport', 'Transport'), ('Waste Management', 'Waste Management'), ('Road Infrastructure', 'Road Infrastructure'), ('Public Safety', 'Public Safety'), ('General', 'General')], default='General', max_length=100)),
                ('sub_category', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('details', models.TextField()),
                ('ai_category', models.CharField(blank=True, max_length=100, null=True)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20)),
                ('sentiment_score', models.FloatField(default=0.0)),
                ('sentiment_label', models.CharField(default='Neutral', max_length=20)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('urgency_level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected'), ('On Hold', 'On Hold'), ('Escalated', 'Escalated')], default='Pending', max_length=20)),
                ('escalation_level', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='complaints/images/%Y/%m/%d/')),
                ('document', models.FileField(blank=True, null=True, upload_to='complaints/documents/%Y/%m/%d/')),
                ('video', models.FileField(blank=True, null=True, upload_to='complaints/videos/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('citizen_feedback', models.TextField(blank=True, null=True)),
                ('citizen_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('upvotes', models.PositiveIntegerField(default=0)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='landing_page.department')),
            ],
            options={
                'verbose_name': 'Complaint',
                'verbose_name_plural': 'Complaints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIAnalysisLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('category', 'Category Classification'), ('sentiment', 'Sentiment Analysis'), ('priority', 'Priority Prediction'), ('urgency', 'Urgency Detection'), ('spam', 'Spam Detection'), ('summary', 'Text Summarization')], max_length=50)),
                ('input_text', models.TextField()),
                ('result', models.JSONField()),
                ('confidence', models.FloatField(default=0.0)),
                ('model_version', models.CharField(default='1.0', max_length=50)),
                ('processing_time', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_logs', to='landing_page.complaint')),
            ],
            options={
                'verbose_name': 'AI Analysis Log',
                'verbose_name_plural': 'AI Analysis Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_type', models.CharField(choices=[('status_update', 'Status Update'), ('note', 'Note'), ('escalation', 'Escalation'), ('assignment', 'Assignment'), ('resolution', 'Resolution')], default='note', max_length=20)),
                ('update_text', models.TextField()),
                ('internal_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='updates/attachments/%Y/%m/%d/')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='landing_page.complaint')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Complaint Update',
                'verbose_name_plural': 'Complaint Updates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['status', 'priority'], name='landing_pag_status_aff752_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['category', 'created_at'], name='landing_pag_categor_421b40_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['department', 'status'], name='landing_pag_departm_dc7788_idx'),
        ),
    ]
