# Generated by Django 4.2 on 2025-12-30 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_id', models.CharField(editable=False, max_length=36, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='complaint_images/')),
                ('ai_category', models.CharField(blank=True, max_length=100, null=True)),
                ('ai_priority', models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20, null=True)),
                ('ai_sentiment', models.CharField(blank=True, choices=[('Very Negative', 'Very Negative'), ('Negative', 'Negative'), ('Neutral', 'Neutral'), ('Positive', 'Positive'), ('Very Positive', 'Very Positive')], max_length=20, null=True)),
                ('ai_confidence', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Submitted', max_length=20)),
                ('assigned_to', models.CharField(blank=True, max_length=100, null=True)),
                ('resolution_details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
