# Generated by Django 5.2.9 on 2026-02-06 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_feedback'),
        ('pulse_admin', '0004_departmentuser_delete_alertrule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department handling this complaint', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='pulse_admin.department'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='department_category',
            field=models.CharField(blank=True, help_text='Store category name for quick filtering', max_length=20, null=True),
        ),
    ]
