FAQ_KB = [
    {"keywords": ["how can i submit a complaint", "submit a complaint", "submit complaint", "how can i submit"],
     "answer": "To submit a complaint, go to Dashboard → Lodge Complaint, fill in the details, and click Submit."},
    {"keywords": ["how do i lodge a complaint", "lodge a complaint", "lodge complaint", "how do i lodge"],
     "answer": "You can lodge a complaint from the Dashboard by clicking the “Lodge Complaint” button."},
    {"keywords": ["what details are required to submit a complaint", "what details", "required details"],
     "answer": "You need a category, description, location, and optional images."},
    {"keywords": ["can i upload images with my complaint", "upload images", "attachments", "images"],
     "answer": "Yes, you can upload images to support your complaint."},
    {"keywords": ["how can i track my complaint", "track my complaint", "track complaint", "how to track"],
     "answer": "Go to Track Complaint and enter your Complaint ID."},
    {"keywords": ["where can i find my complaint id", "find my complaint id", "complaint id location"],
     "answer": "Your Complaint ID is available in the My Complaints page and confirmation email."},
    {"keywords": ["what does pending mean", "pending meaning", "pending"],
     "answer": "Pending means your complaint is waiting for department action."},
    {"keywords": ["what does resolved mean", "resolved meaning", "resolved"],
     "answer": "Resolved means the department has completed action on your complaint."},
    {"keywords": ["what does in progress mean", "in progress meaning", "in progress"],
     "answer": "In Progress means the department is currently working on your complaint."},
    {"keywords": ["why is my complaint still pending", "still pending", "why pending"],
     "answer": "Your complaint may be under review or awaiting department response."},
    {"keywords": ["where can i see all my complaints", "see all my complaints", "all my complaints", "where can i see my complaints"],
     "answer": "You can see all your complaints in the My Complaints section."},
    {"keywords": ["can i see other citizens complaints", "other citizens complaints", "view others complaints"],
     "answer": "No, for privacy reasons, you can only view your own complaints."},
    {"keywords": ["how do i update my profile", "update my profile", "edit profile"],
     "answer": "Go to Profile, update your details, and click Update Profile."},
    {"keywords": ["how can i change my password", "change my password", "change password"],
     "answer": "Go to Profile and select Change Password."},
    {"keywords": ["can i change my username", "change username"],
     "answer": "No, usernames cannot be changed after registration."},
    {"keywords": ["what is civic pulse", "what is civic pulse"],
     "answer": "Civic Pulse is a smart civic engagement platform for citizen complaints and feedback."},
    {"keywords": ["who handles my complaint", "who handles complaint", "handled by"],
     "answer": "Your complaint is handled by the relevant government department."},
    {"keywords": ["will i get updates on my complaint", "get updates", "updates on my complaint"],
     "answer": "Yes, updates appear in your dashboard and notifications."},
    {"keywords": ["how long does complaint resolution take", "how long", "resolution time"],
     "answer": "Resolution time depends on the department and issue type."},
    {"keywords": ["can i reopen a resolved complaint", "reopen resolved", "reopen complaint"],
     "answer": "Currently, resolved complaints cannot be reopened."},
    {"keywords": ["what categories are available for complaints", "categories available", "complaint categories"],
     "answer": "Categories include Healthcare, Transport, Electricity, Education, Public Safety, and more."},
    {"keywords": ["what is the ai assistant", "ai assistant", "what is the ai assistant"],
     "answer": "The AI Assistant helps guide you on complaints and platform usage."},
    {"keywords": ["can the ai assistant file complaints", "assistant file complaints", "ai submit complaints"],
     "answer": "No, the assistant can guide you but cannot submit complaints for you."},
    {"keywords": ["is my data secure", "data secure", "privacy"],
     "answer": "Yes, Civic Pulse uses secure systems to protect your data."},
    {"keywords": ["i forgot my password", "forgot my password", "forgot password"],
     "answer": "Use the Forgot Password option on the login page."},
    {"keywords": ["i cannot submit a complaint", "cannot submit", "unable to submit"],
     "answer": "Please check required fields and try again."},
    {"keywords": ["my complaint status looks wrong", "status looks wrong", "status wrong"],
     "answer": "Please wait for updates or contact support if the issue continues."},
    {"keywords": ["how do i contact support", "contact support", "support"],
     "answer": "You can contact support using the Contact section or support email."},
    {"keywords": ["can i delete my complaint", "delete my complaint", "remove complaint"],
     "answer": "No, submitted complaints cannot be deleted."},
    {"keywords": ["what should i do if my issue is urgent", "urgent issue", "urgent"],
     "answer": "Submit the complaint with complete details so it can be prioritized."},
    {"keywords": ["can i submit multiple complaints", "submit multiple complaints", "multiple complaints"],
     "answer": "Yes, you can submit multiple complaints."},
    {"keywords": ["do i need to pay to submit a complaint", "pay to submit", "pay"],
     "answer": "No, submitting complaints is completely free."},
    {"keywords": ["is civic pulse a government platform", "government platform", "is civic pulse government"],
     "answer": "Civic Pulse works with government departments to address citizen issues."},
    {"keywords": ["can i use civic pulse on mobile", "mobile", "mobile browser"],
     "answer": "Yes, Civic Pulse works on mobile and desktop browsers."},
    {"keywords": ["what if my question is not answered here", "question not answered", "not answered"],
     "answer": "Please submit a complaint or contact support for further help."}
]
